name: Publish to PyPI

on:
  release:
    types: [published]      # runs only when you create a GitHub Release

permissions:
  id-token: write           # OIDC token for PyPI
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python -m pip install --upgrade build
      - run: python -m build        # creates dist/*.whl and dist/*.tar.gz
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true       # don’t fail if version already uploaded
